# -*- coding: utf-8 -*-
"""CorreccionADN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jZJBx7yJbm5xxyUpoLt8wDQlYGGiuSsN
"""

secuencia = input("Introduzca la secuencia: ")

secuencia = secuencia.upper()
if len(secuencia) % 3 == 0:
	print("La secuencia es correcta")
elif len(secuencia) % 3 == 1:
	print("Se eliminó un nucleótido sobrante.")
	secuencia = secuencia[:len(secuencia)-1]
else:
	print("Se eliminaron dos nucleótidos sobrantes.")
	secuencia = secuencia[:len(secuencia)-2]

print("Secuencia:")
print(secuencia)

input()